In [1]:
import numpy as np

## tipos de array:

- Possui apenas uma dimensão. Será comumente chamado de vetor ou vector;
- 2 dimensões. Será comumente chamado de matriz ou matrix;
- Possui 3 ou mais dimensões. Será comumente chamado de tensor.

## Criando uma Array

In [2]:
## array 1 dimensão - vetor
a = np.array([1,2,3,4,5,6])

# lista
list = [1,2,3,4,5]

print(type(a))
print(type(list))

<class 'numpy.ndarray'>
<class 'list'>


In [3]:
## array 2 dimensão - matrix
b = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])

print (b)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [4]:
## array 3 dimensão - tensor
c = np.array([[1,2,3,4,5,6], [6,5,4,3,2,1], [1,2,3,4,5,6]],)

print (c)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [1 2 3 4 5 6]]


In [5]:
## Podemos criar uma matrix de valor zero
zero_array = np.zeros(100)

print (zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [6]:
## Podemos organizar essa matrix com a estrutura que queremos
shape = [5,3,6]
zero_array = np.zeros(shape)

print (zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [7]:
## Podemos fazer essa mesma estrutura com valor positivo usando o np.ones em vez de np.zeros
shape = [5,3,6]
one_array = np.ones(shape)

print (one_array)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [8]:
## valores aleatórios
vazio = np.empty(4)

print (vazio)

[4.88708958e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]


In [9]:
## Criar array em uma sequência
arange = np.arange(10)

print(arange)

## Podemos modificar da forma que quisermos

## intervalo inicial, intervalo final, quanto em quanto)
arange_10 = np.arange(10, 50, 10)

print(arange_10)

[0 1 2 3 4 5 6 7 8 9]
[10 20 30 40]


In [10]:
## criar uma sequencia uniforme
array_linear = np.linspace(1,10,5)

print (array_linear)

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
## informações de um numpy
shape = [5,3,6]
zero_array = np.zeros(shape)

print (zero_array.shape) ## estrutura
print (zero_array.size) ## total de dados
print (zero_array.ndim) # numero de dimensões "por exemplo deu 3, sendo um tensor"

(5, 3, 6)
90
3


In [12]:
## Podemos converter um tensor para vetor
print(c.flatten())


[1 2 3 4 5 6 6 5 4 3 2 1 1 2 3 4 5 6]


In [24]:
## Podemos comparar dois arrays e verificar se eles são iguais
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])

semelhanca = np.array_equal(a, b)

if semelhanca == True:
    print("Há semelhança entre A e B")
else:
    print("Não existe semelhança entre A e B")

Há semelhança entre A e B
